"""initial_schema

Revision ID: 21b1543c873d
Revises: 
Create Date: 2026-07-26 17:49:11.621006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b1543c873d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_activities_delayed', 'activities', ['project_id'], unique=False, postgresql_where=sa.text('actual_percentage < planned_percentage'))
    op.create_index('idx_activities_evm_calc', 'activities', ['project_id'], unique=False, postgresql_include={'bac', 'planned_percentage', 'actual_percentage', 'actual_cost'})
    op.create_index('idx_activities_project_created', 'activities', ['project_id', 'created_at'], unique=False, postgresql_using='btree')
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_projects_created_at'), table_name='projects')
    op.create_index('idx_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_projects_updated_at_desc', 'projects', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_projects_updated_at_desc', table_name='projects')
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.create_index(op.f('idx_projects_created_at'), 'projects', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index('idx_activities_project_created', table_name='activities', postgresql_using='btree')
    op.drop_index('idx_activities_evm_calc', table_name='activities', postgresql_include={'bac', 'planned_percentage', 'actual_percentage', 'actual_cost'})
    op.drop_index('idx_activities_delayed', table_name='activities', postgresql_where=sa.text('actual_percentage < planned_percentage'))
    op.alter_column('activities', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
